### ISSUE TITLE
[iOS] Cannot connect to server with http-only

### ISSUE THREAD

**Issue by schwier-xyz** [hoarder-app/hoarder#288]
Hello! I face a bug on the iOS app when connecting to a server which only supports http (Tailscale).

I receive the error message: Network request failed

I also tested to use a public domain (google.com) as sever and the difference in error messages between https://google.com http://google.com suggest it's an issue with http-only connections not being accepted.

I saw that similar issues existed in the past for the Firefox plugin.
![image](https://github.com/hoarder-app/hoarder/assets/157237122/3f71d29d-b4ce-4372-84c2-1f31f0be82db)
![image](https://github.com/hoarder-app/hoarder/assets/157237122/46bf8e95-e304-4f13-ab21-64ea1037ad4e)
![image](https://github.com/hoarder-app/hoarder/assets/157237122/154e2fab-4325-496e-b869-b566b00118ad)

**Comment by MohamedBassem** [comment]
hmmm, this should have been fixed in iOS in https://github.com/hoarder-app/hoarder/commit/c53a0dd33041f1a21896e47b0a6fa49032f05600 a while ago. I think we really need this "test connection" button in the app.

**Comment by schwier-xyz** [comment]
I'm no expert in React Native (that's what the app is using, right?) but I found the following articles mentioning that the App Transport Security settings are overwritten when switching from Debug to Release.

Is this relevant?

https://github.com/facebook/react-native/issues/41874
https://www.reddit.com/r/reactnative/comments/l8vppl/solution_not_having_to_turn_onoff_app_transport/

**Comment by hongruilin** [comment]
> hmmm, this should have been fixed in iOS in [c53a0dd](https://github.com/hoarder-app/hoarder/commit/c53a0dd33041f1a21896e47b0a6fa49032f05600) a while ago. I think we really need this "test connection" button in the app.

Hello, currently Android can indeed connect, but the iOS system still cannot. I have already downloaded the latest version

**Comment by glassuse** [comment]
I cannot connect with iOS either

**Comment by AsocPro** [comment]
That’s a great feature. This is what my diagnostic report shows:
`Running connection test ...

Using address: http://ADDRESS:PORT/

Network connection failed: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

ADDRESS and PORT have been redacted as they are internal values but were the host name and port I entered on the address field.

**Comment by GianmarcoFolchi** [comment]
Hi, I have the same issue, but no solution has been posted

**Comment by Doc-Steve** [comment]
I had success by replacing the dns name with the IP address.

**Comment by iamzenz** [comment]
I ran into the same issue using http with a tailscale ip address. 

Replacing the ip with the device name solved the issue.

**Comment by linearpeanut** [comment]
I tried name and IP. With name I go the App Transport Security policy error and with IP I get 
`The file "health" couldn't be opened because there is no such file`

**Comment by messytoolshed** [comment]
> Hello! I face a bug on the iOS app when connecting to a server which only supports http (Tailscale).
> 
> I receive the error message: Network request failed
> 
> I also tested to use a public domain (google.com) as sever and the difference in error messages between https://google.com http://google.com suggest it's an issue with http-only connections not being accepted.
> 
> I saw that similar issues existed in the past for the Firefox plugin. ![image](https://private-user-images.githubusercontent.com/157237122/346693596-3f71d29d-b4ce-4372-84c2-1f31f0be82db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDI2NDYsIm5iZiI6MTczNDk0MjM0NiwicGF0aCI6Ii8xNTcyMzcxMjIvMzQ2NjkzNTk2LTNmNzFkMjlkLWI0Y2UtNDM3Mi04NGMyLTFmMzFmMGJlODJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwODI1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzBmNTgxYTFmZWY3YjJjZWY2YThjZTM1NTZlOGQ0N2E4MGIxNzk1M2I0YTVhM2RjNzc0OWU1ZGMyNzQwNjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OvLZE2wD88mHrxVcHgcP-6PQFYMrV-UenGiC7UH19eA) ![image](https://private-user-images.githubusercontent.com/157237122/346693709-46bf8e95-e304-4f13-ab21-64ea1037ad4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDI2NDYsIm5iZiI6MTczNDk0MjM0NiwicGF0aCI6Ii8xNTcyMzcxMjIvMzQ2NjkzNzA5LTQ2YmY4ZTk1LWUzMDQtNGYxMy1hYjIxLTY0ZWExMDM3YWQ0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwODI1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjNhNzI3YTBjNDVlMDdhZDM2ZDZjMWUxYjgzNTdhZThlY2UyYzM2ZWRlYWQ3MmM0MGJjMGQ1ZTFmOWY5MGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wwBQuN5Ko9YNbdH1jsJ9fQH2c5-KQhkY0fU7qLRlik8) ![image](https://private-user-images.githubusercontent.com/157237122/346693732-154e2fab-4325-496e-b869-b566b00118ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDI2NDYsIm5iZiI6MTczNDk0MjM0NiwicGF0aCI6Ii8xNTcyMzcxMjIvMzQ2NjkzNzMyLTE1NGUyZmFiLTQzMjUtNDk2ZS1iODY5LWI1NjZiMDAxMThhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwODI1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFjM2IzZjkwNGNiYWQzNDBmMjMxNDMzMTJmZDYxNTY4YmEwNDEyZmE3MzA3MGIxYWY2YjhiMGIwYTZhMTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iBVFFJ4M6HPR676YtG7pCFNHtz-gObGfNSr504SO2jo)

If you are hosting the hoarder server behind an IP-address in the range 100.64.0.0 - 100.127.255.255 then it is highly unlikely that you will be able to connect to it from outside of your home (assuming you are hosting the server at home) because that IP-address range is not reachable over the Internet. This is not application related nor is it related to http/https but it is related to network reachability. You will need to host it on a public hosting service or ask your ISP to assign you a public IP-address, if at all possible. See also https://en.wikipedia.org/wiki/Carrier-grade_NAT

**Comment by Fiala06** [comment]
> I tried name and IP. With name I go the App Transport Security policy error and with IP I get `The file "health" couldn't be opened because there is no such file`

I have this same issue. :/

**Comment by vex9z7** [comment]
> > I tried name and IP. With name I go the App Transport Security policy error and with IP I get `The file "health" couldn't be opened because there is no such file`
> 
> I have this same issue. :/

same here, could we reopen the issue and schedule a fix?

**Comment by shawnzxx** [comment]
> If you are hosting the hoarder server behind an IP-address in the range 100.64.0.0 - 100.127.255.255 then it is highly unlikely that you will be able to connect to it from outside of your home (assuming you are hosting the server at home) because that IP-address range is not reachable over the Internet. This is not application related nor is it related to http/https but it is related to network reachability. You will need to host it on a public hosting service or ask your ISP to assign you a public IP-address, if at all possible. See also https://en.wikipedia.org/wiki/Carrier-grade_NAT

I don't agree, since most of us are hosting the `Hoarder server via Tailscale` which suppose to use point-to-point technology to connect all clients into the same home network cluster, I tested other self-hosted app like Plex server,  it's Plex client app can connect via HTTP IP address directly.

**Comment by deandmx** [comment]
If you're using TSDProxy [https://github.com/almeidapaulopt/tsdproxy](https://github.com/almeidapaulopt/tsdproxy) you can use the address ```
https://hoarder.funny-name.ts.net
``` that you get with the service.

**Comment by a2hill** [comment]
While this issue is closed, the problem still exists. Is this being tracked elsewhere? 

Like the others here I cannot access hoarder from the app via http using either the tailscale hostname (ending in `.ts.net`) nor the tailscale ip address. However like @verisimillipede said, using the device name does work (for instance if your ts url was `mydevice.my-magic-dns-prefix.ts.net` you can just use `http://mydevice:<hoarder-port-number>`).

Rather than trying to make http work, is it possible to support https access to Horder? I don't see anything in the configuration documents that specifies how to pass certificate information to the service

**Comment by rekirk82** [comment]
Came here with this issue also. I can't log into the iOS app from within my own network, but I can login from safari on the same device and login to hoarder just fine. :(

**Comment by TimbaJadenJorn** [comment]
For the iOS app, try allowing Local Network Access:
Settings -> Apps -> Hoarder App -> Local Network
