### ISSUE TITLE
HIghlighting is preventing copy/paste

### ISSUE THREAD

**Issue by frankofno** [hoarder-app/hoarder#920]
Is there a way to disable auto-highlighting?

I usually want to copy/paste text from the saved pages. In hoarder this is not possible at all. Instead, the hightling options pops up. I can only select a color, but i can not copy/paste the text, unless I visit the original page again.

Therefor I would suggest to make highlighting optional and bring back copy/paste.

**Comment by MohamedBassem** [comment]
This is fixed in the nightly build (https://github.com/hoarder-app/hoarder/commit/1ec21b67df64992bf472fc17bc3842369aa313a7) and will be available in the next release.

**Comment by frankofno** [comment]
> This is fixed in the nightly build ([1ec21b6](https://github.com/hoarder-app/hoarder/commit/1ec21b67df64992bf472fc17bc3842369aa313a7)) and will be available in the next release.

I just updated to v. 0.22.0 - the highlight bug is still there.
